### ISSUE TITLE
Beef up ReadMe

### ISSUE THREAD

**Issue by knissley** [Tetlier/Atelier#30]
https://github.com/Tetlier/Atelier/blob/15b94832a0acc208a707ba7db71335a14f6adde0/README.md?plain=1#L1

The ReadMe hasn't been a focus yet, but as we get to the Polish sprint make sure to create a Readme file to outline how to get the project up and running, and key information you want to convey about it.

This is the first page that will show when anyone researches your repository, so make it welcoming. Feel free to outline your efforts and reference materials demonstrating your work on the project, and remember to include instructions on how to use those npm scripts.  

For this FEC project, a lot of your work is the visual presentation of the app.  If you don’t have the application deployed, consider taking screen captures of the app and its features to demo your work.

**Comment by codingavatar** [comment]
Thank you, we will definitely work on our ReadMe file!

**Comment by codingavatar** [comment]
@knissley, we have updated our ReadMe and incorporated screen captures. Please review and let us know if there can be any improvements! Thanks!
