### ISSUE TITLE
Div in App.js

### ISSUE THREAD

**Issue by knissley** [Tetlier/Atelier#31]
https://github.com/Tetlier/Atelier/blob/15b94832a0acc208a707ba7db71335a14f6adde0/client/src/components/App.jsx#L94

For consistency's sake with the rest of the App jsx, I'd remove the div with id reviews and place just the reviews component there. This might have come into play from considering CSS, but you should still be able to accomplish any styling this provides by putting the div inside the reviews component instead.

**Comment by codingavatar** [comment]
Thanks, Austin moved this id!
