### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by knissley** [Tetlier/Atelier#34]
https://github.com/Tetlier/Atelier/blob/15b94832a0acc208a707ba7db71335a14f6adde0/client/src/components/Overview/ImageCarousel.jsx#L4

It might be too late in the process to warrant changing this, but for future consideration: I'd strongly recommend against using jQuery for the purposes that I've seen so far in this project. The uses I've seen like animating, getting dimensions of an HTML element, etc. can all be handled with vanilla JS and maybe a bit of React. For that reason I'd caution against bringing in a library, especially one as large as jQuery, to handle these few cases.

On the job it's likely they wouldn't allow adding a library as large as jQuery without very strong reasons, so it's good to learn how to handle these tasks in vanilla Javascript.

**Comment by codingavatar** [comment]
That makes a lot of sense. We will keep that in mind for future projects!
